apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-container-image
spec:
  entrypoint: kaniko-build-flow
  arguments:
    parameters:
    - name: model-version

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: fetch-model
          template: download-model
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: kaniko-build
          template: kaniko
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: tag-model-staging
          template: set-mlflow-alias
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: deploy-to-staging
          template: trigger-deploy
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
            - name: environment
              value: "staging"

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          MAX_RETRIES=5
          i=1

          while [ $i -le $MAX_RETRIES ]; do
            echo "Attempt $i of $MAX_RETRIES: Cloning repo..."
            git clone --branch workflow https://github.com/M0n4GPT/Vision-to-Vintage-AIs-Take-on-Classical-Art.git /mnt/workspace && break
            echo "Git clone failed. Retrying in 5 seconds..."
            i=$((i + 1))
            sleep 5
          done

          if [ ! -d /mnt/workspace/.git ]; then
            echo "Git clone failed after $MAX_RETRIES attempts."
            exit 1
          fi
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: download-model
    inputs:
      parameters:
      - name: model-version
    container:
      image: python:3.11-slim
      command: [sh, -c]
      args:
        - |
          pip install mlflow-skinny
          export MLFLOW_TRACKING_URI=http://mlflow.vision-to-vintage-platform.svc.cluster.local:8000
          mkdir -p /tmp/mlflow_model

          echo "Downloading MLflow model artifacts..."
          mlflow artifacts download \
            --artifact-uri models:/VisionToVintageStyleModel/{{inputs.parameters.model-version}} \
            -d /
