---
- name: Hello, world - use Ansible to run a command on each host
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Run 'hostname' command
      ansible.builtin.command: hostname
      register: hostname_output

    - name: Show hostname output
      ansible.builtin.debug:
        msg: "The hostname of {{ inventory_hostname }} is {{ hostname_output.stdout }}"
